name: Daily Setup Run

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行（北京时间 8 点）
  workflow_dispatch:      # 允许手动触发

jobs:
  execute-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 使用项目需要的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .

    - name: Execute setup.py
      run: python setup.py
