name: Daily Setup Run
on:
  schedule:
    # 每天 UTC 时间 20:00 对应北京时间 4:00
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  run-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run setup.py
        run: python setup.py
